sources:
  - name: thelook_ecommerce  # <--- Make sure this has the _ecommerce suffix
    database: bigquery-public-data
    schema: thelook_ecommerce
    tables:
      - name: users
      - name: orders
      - name: order_items
      - name: products
      - name: distribution_centers